### ISSUE TITLE
'priorsense' does not work for brms models and github installation fails also

### ISSUE THREAD

**Issue by AndHofma** [n-kall/priorsense#59]
Salut,
I was trying to install the most current development version of priorsense to use for brms models, which was recommended. The installation via: 

install.packages("remotes")
remotes::install_github("n-kall/priorsense", ref = "development")

fails with this error message:

"
✔  checking for file ‘/tmp/Rtmp0VUkVk/remotes380e04d513b18/n-kall-priorsense-ebea668/DESCRIPTION’ (720ms)
─  preparing ‘priorsense’:
E  checking DESCRIPTION meta-information
   Malformed Authors@R field:
     <text>:8:0: unexpected end of input
   6:              person("Giorgio", "Micaletto", role = c("ctb")
   7:              )
     ^
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
Error: Failed to install 'priorsense' from GitHub:
  System command 'R' failed, exit status: 1, stdout & stderr were printed
  "
  
 I looked into the description file but don't see any problem.
 Can this error be solved so that I can install the package via github?
 
 Thanks very much for your time and effort,
Andrea

**Comment by n-kall** [comment]
Thanks for reporting this! I'll fix the issue shortly. But actually for brms compatibility you can use the CRAN version / main branch of priorsense but you'll need the github version of brms `devtools::install_github("paul-buerkner/brms")` until a new version of `brms` is released on CRAN

**Comment by AndHofma** [comment]
Awesome - thanks for the quick reply!
Will follow your suggestion.
Have a nice day!
